{{ if .Values.migrateJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-sites-{{ template "erpnext.fullname" . }}-{{ date "20060102150405" .Release.Now }}
spec:
  backoffLimit: 1
  template:
    spec:
      securityContext:
        supplementalGroups: [1000]
      {{ if .Values.migrateJob.enable }}
      initContainers:
      - name: backup
        image: "{{ .Values.pythonImage.repository }}:{{ .Values.pythonImage.tag }}"
        args: ["backup"]
        imagePullPolicy: {{ .Values.pythonImage.pullPolicy }}
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
      {{ end }}
      containers:
      - name: migrate
        image: "{{ .Values.pythonImage.repository }}:{{ .Values.pythonImage.tag }}"
        args: ["migrate"]
        env:
          - name: "MAINTENANCE_MODE"
            value: "1"
        imagePullPolicy: {{ .Values.pythonImage.pullPolicy }}
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
      restartPolicy: Never
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            claimName: {{ template "erpnext.fullname" . }}
            readOnly: false
{{ end }}
