name: Test Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build_bench:
    name: Test Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install k3d
        run: curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
      - name: Run Tests
        run: |
          helm lint erpnext
          ./tests/script.sh
